Update

diff --git a/uit-tss-toolbox_2.0-1_amd64/usr/sbin/uit-git-script b/uit-tss-toolbox_2.0-1_amd64/usr/sbin/uit-git-script
--- a/uit-tss-toolbox_2.0-1_amd64/usr/sbin/uit-git-script
+++ b/uit-tss-toolbox_2.0-1_amd64/usr/sbin/uit-git-script
@@ -1,7 +1,13 @@
 #!/bin/bash
 
-if [[ "$EUID" > 0 ]]
-  then echo "Please run as root"
+if [[ "$EUID" > 0 ]]; then 
+  echo "Please run as root. Exiting..."
+  exit 1
+fi
+
+if [[ ! -f /home/cameron/.uit-passwd ]]; then
+  echo "/home/cameron/.uit-passwd is missing. Exiting..."
+  echo "Make sure DB_ADMIN_PASSWD, DB_CLIENT_PASSWORD, DB_WEB_USER_PASSWD, and DB_WEB_PASSWORD are all set."
   exit 1
 fi
 
