Update uit-tss-client

diff --git a/uit-tss-toolbox_2.0-1_amd64/var/lib/UIT-TSS-TOOLBOX/uit-tss-client_2.0-1_amd64/usr/sbin/uit-tss-client b/uit-tss-toolbox_2.0-1_amd64/var/lib/UIT-TSS-TOOLBOX/uit-tss-client_2.0-1_amd64/usr/sbin/uit-tss-client
--- a/uit-tss-toolbox_2.0-1_amd64/var/lib/UIT-TSS-TOOLBOX/uit-tss-client_2.0-1_amd64/usr/sbin/uit-tss-client
+++ b/uit-tss-toolbox_2.0-1_amd64/var/lib/UIT-TSS-TOOLBOX/uit-tss-client_2.0-1_amd64/usr/sbin/uit-tss-client
@@ -847,7 +847,7 @@ function vrfyDisk_Shred {
 	echo "Looking for non-${CHAR}'s on ${CLIENTDISK}...."
 
 	if [[ $PCNTOFSECTOR == '100' ]]; then
-		FULLVRFY=$(pv /dev/${CLIENTDISK} | grep -oP -m 1 "[^${CHAR}]" | head -n 1)
+		FULLVRFY=$(pv /dev/${CLIENTDISK} | grep --quiet --text -v -m 1 "${CHAR}")
 		if [[ ${PIPESTATUS[1]} = "1" ]]; then
         	echo "${BOLD}The drive ${CLIENTDISK} is completely and securely wiped.${RESET}"
 			PROCFAIL='0'
@@ -869,7 +869,7 @@ function vrfyDisk_Shred {
 		MATHONE=$(shuf -i 1-$(( SECTIONSIZEMB / DIVPERSEC )) -n 1)
 		SKIP1=$(( MATHONE + ${a} / 2 ))
     	if [[ $(dd if=/dev/${CLIENTDISK} bs=${BS} count=${COUNT1} skip=${SKIP1} iflag=fullblock status=none 2>/dev/null \
-        	| grep --quiet -oP -m 1 [^${CHAR}]; echo $?) == '0' ]]; then
+        	| grep --quiet --text -v -m 1 "${CHAR}"; echo ${PIPESTATUS[1]}) == '0' ]]; then
             	PROCFAIL='1'
             	echo "${BOLD}${RED}Bad bits found on device${RESET}${BOLD} ${CLIENTDISK}${RESET}"
 				echo ""
@@ -881,7 +881,7 @@ function vrfyDisk_Shred {
 		MATHTWO=$(shuf -i 1-$(( SECTIONSIZEMB + SECTIONSIZEMB - SECTIONSIZEMB / DIVPERSEC )) -n 1)
     	SKIP2=$(( MATHTWO + ${a} ))
     	if [[ $(dd if=/dev/${CLIENTDISK} bs=${BS} count=${COUNT2} skip=${SKIP2} iflag=fullblock status=none 2>/dev/null \
-        	| grep --quiet -oP -m 1 [^${CHAR}]; echo $?) == '0' ]]; then
+        	| grep --quiet --text -v -m 1 "${CHAR}"; echo ${PIPESTATUS[1]}) == '0' ]]; then
             	PROCFAIL='1'
             	echo "${BOLD}${RED}Bad bits found on device${RESET}${BOLD} ${CLIENTDISK}${RESET}"
 				echo ""
@@ -897,7 +897,7 @@ function vrfyDisk_Shred {
 	echo ""
 	echo "Verifing the first sector of the disk...."
 	if [[ $(dd if=/dev/${CLIENTDISK} count=${SECTIONSIZEMB} skip=0 iflag=fullblock status=none 2>/dev/null \
-        | grep --quiet -oP -m 1 [^${CHAR}]; echo $?) == '0' && $PROCFAIL == '0' ]]; then
+        | grep --quiet --text -v -m 1 "${CHAR}"; echo ${PIPESTATUS[1]}) == '0' && $PROCFAIL == '0' ]]; then
             	PROCFAIL='1'
             	echo "${BOLD}${RED}Bad bits found on device${RESET}${BOLD} ${CLIENTDISK}${RESET}"
 				echo ""
@@ -907,7 +907,7 @@ function vrfyDisk_Shred {
 	echo "Verifing the last sector of the disk...."
     if [[ $(dd if=/dev/${CLIENTDISK} count=${SECTIONSIZEMB} skip=$(( ${DISKSIZEMB} - ${SECTIONSIZEMB} )) \
 		iflag=fullblock status=none 2>/dev/null \
-        | grep --quiet -oP -m 1 [^${CHAR}]; echo $?) == '0' && $PROCFAIL == '0' ]]; then
+        | grep --quiet --text -v -m 1 "${CHAR}"; echo ${PIPESTATUS[1]}) == '0' && $PROCFAIL == '0' ]]; then
             	PROCFAIL='1'
             	echo "${BOLD}${RED}Bad bits found on device${RESET}${BOLD} ${CLIENTDISK}${RESET}"
 				echo ""
